import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:intl/intl.dart';
import '../../core/constants/app_constants.dart';
import '../../models/booking_model.dart';
import '../../services/firestore_service.dart';
import 'booking_confirmation_screen.dart';

/// Session Booking screen with full form validation.
/// Fields: name, email, phone, package, date, time slot, message.
class BookingScreen extends StatefulWidget {
  final String photographerId;
  final String photographerName;

  const BookingScreen({
    super.key,
    required this.photographerId,
    required this.photographerName,
  });

  @override
  State<BookingScreen> createState() => _BookingScreenState();
}

class _BookingScreenState extends State<BookingScreen> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _emailController = TextEditingController();
  final _phoneController = TextEditingController();
  final _messageController = TextEditingController();

  final FirestoreService _firestoreService = FirestoreService();

  String _selectedPackage = AppConstants.packages.first;
  DateTime? _selectedDate;
  String? _selectedTimeSlot;
  bool _isSubmitting = false;

  // ── Date picker ────────────────────────────────────────────────────────────
  Future<void> _pickDate() async {
    final now = DateTime.now();
    final tomorrow = now.add(const Duration(days: 1));
    final picked = await showDatePicker(
      context: context,
      initialDate: tomorrow,
      firstDate: tomorrow, // Cannot book in the past
      lastDate: now.add(const Duration(days: 365)),
    );
    if (picked != null) setState(() => _selectedDate = picked);
  }

  // ── Submit booking ─────────────────────────────────────────────────────────
  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;

    if (_selectedDate == null) {
      _showError('Please select a booking date.');
      return;
    }
    if (_selectedTimeSlot == null) {
      _showError('Please select a time slot.');
      return;
    }

    setState(() => _isSubmitting = true);

    try {
      final user = FirebaseAuth.instance.currentUser;
      final clientId = user?.uid ?? 'anonymous';

      final booking = BookingModel(
        bookingId: '', // generated by FirestoreService
        clientId: clientId,
        photographerId: widget.photographerId,
        photographerName: widget.photographerName,
        clientName: _nameController.text.trim(),
        clientEmail: _emailController.text.trim(),
        clientPhone: _phoneController.text.trim(),
        packageName: _selectedPackage,
        bookingDate: DateFormat('yyyy-MM-dd').format(_selectedDate!),
        timeSlot: _selectedTimeSlot!,
        message: _messageController.text.trim(),
        status: 'pending',
      );

      // async/await write to Firestore — generates unique booking ID
      final bookingId = await _firestoreService.saveBooking(booking);

      if (!mounted) return;
      // Navigate to confirmation screen
      Navigator.of(context).pushReplacement(
        MaterialPageRoute(
          builder: (_) => BookingConfirmationScreen(
            bookingId: bookingId,
            photographerName: widget.photographerName,
            packageName: _selectedPackage,
            bookingDate: _selectedDate!,
            timeSlot: _selectedTimeSlot!,
          ),
        ),
      );
    } catch (e) {
      // Show error without losing form data
      _showError('Booking failed: ${e.toString()}');
    } finally {
      if (mounted) setState(() => _isSubmitting = false);
    }
  }

  void _showError(String message) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text(message),
        backgroundColor: Colors.red.shade700,
        behavior: SnackBarBehavior.floating,
      ),
    );
  }

  @override
  void dispose() {
    _nameController.dispose();
    _emailController.dispose();
    _phoneController.dispose();
    _messageController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Book ${widget.photographerName}'),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.fromLTRB(20, 16, 20, 32),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Progress indicator — step 3 of 3
              _buildProgressBar(),
              const SizedBox(height: 24),

              // ── Section: Client Info ────────────────────────────────
              _sectionLabel('Your Information'),
              const SizedBox(height: 12),

              TextFormField(
                controller: _nameController,
                textCapitalization: TextCapitalization.words,
                decoration: const InputDecoration(
                  labelText: 'Full Name',
                  prefixIcon: Icon(Icons.person_outline),
                ),
                validator: (v) =>
                    v == null || v.trim().isEmpty ? 'Name is required' : null,
              ),
              const SizedBox(height: 14),

              TextFormField(
                controller: _emailController,
                keyboardType: TextInputType.emailAddress,
                decoration: const InputDecoration(
                  labelText: 'Email Address',
                  prefixIcon: Icon(Icons.email_outlined),
                ),
                validator: (v) {
                  if (v == null || v.trim().isEmpty) return 'Email is required';
                  if (!RegExp(r'^[^@]+@[^@]+\.[^@]+').hasMatch(v.trim())) {
                    return 'Enter a valid email address';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 14),

              TextFormField(
                controller: _phoneController,
                keyboardType: TextInputType.phone,
                decoration: const InputDecoration(
                  labelText: 'Phone Number',
                  prefixIcon: Icon(Icons.phone_outlined),
                ),
                validator: (v) {
                  if (v == null || v.trim().isEmpty) {
                    return 'Phone number is required';
                  }
                  if (!RegExp(r'^\+?[0-9]{8,15}$').hasMatch(v.trim())) {
                    return 'Enter a valid phone number';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 24),

              // ── Section: Session Details ────────────────────────────
              _sectionLabel('Session Details'),
              const SizedBox(height: 12),

              // Package selector
              DropdownButtonFormField<String>(
                initialValue: _selectedPackage,
                decoration: const InputDecoration(
                  labelText: 'Photography Package',
                  prefixIcon: Icon(Icons.card_membership_outlined),
                ),
                items: AppConstants.packages
                    .map((pkg) => DropdownMenuItem(
                          value: pkg,
                          child: Text('$pkg Package'),
                        ))
                    .toList(),
                onChanged: (v) {
                  if (v != null) setState(() => _selectedPackage = v);
                },
              ),
              const SizedBox(height: 14),

              // Date picker
              InkWell(
                onTap: _pickDate,
                borderRadius: BorderRadius.circular(12),
                child: InputDecorator(
                  decoration: InputDecoration(
                    labelText: 'Session Date',
                    prefixIcon: const Icon(Icons.calendar_today_outlined),
                    filled: true,
                    fillColor: Colors.grey.shade100,
                    border: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(12),
                      borderSide: BorderSide.none,
                    ),
                  ),
                  child: Text(
                    _selectedDate == null
                        ? 'Tap to select a date'
                        : DateFormat('EEEE, dd MMMM yyyy').format(_selectedDate!),
                    style: TextStyle(
                      color: _selectedDate == null
                          ? Colors.grey.shade500
                          : const Color(AppConstants.primaryColor),
                    ),
                  ),
                ),
              ),
              const SizedBox(height: 14),

              // Time slot selector
              _sectionLabel('Time Slot'),
              const SizedBox(height: 10),
              Wrap(
                spacing: 8,
                runSpacing: 8,
                children: AppConstants.timeSlots.map((slot) {
                  final selected = _selectedTimeSlot == slot;
                  return ChoiceChip(
                    label: Text(slot),
                    selected: selected,
                    selectedColor: const Color(AppConstants.primaryColor),
                    backgroundColor: const Color(0xFFF0EBE3),
                    labelStyle: TextStyle(
                      color: selected
                          ? Colors.white
                          : const Color(AppConstants.primaryColor),
                      fontWeight: selected ? FontWeight.bold : FontWeight.normal,
                      fontSize: 12,
                    ),
                    onSelected: (_) =>
                        setState(() => _selectedTimeSlot = slot),
                  );
                }).toList(),
              ),
              const SizedBox(height: 20),

              // Optional message
              TextFormField(
                controller: _messageController,
                maxLines: 3,
                decoration: const InputDecoration(
                  labelText: 'Message (optional)',
                  hintText: 'Any specific requirements or questions…',
                  prefixIcon: Icon(Icons.message_outlined),
                  alignLabelWithHint: true,
                ),
              ),
              const SizedBox(height: 32),

              // Submit
              ElevatedButton(
                onPressed: _isSubmitting ? null : _submit,
                child: _isSubmitting
                    ? const SizedBox(
                        height: 22,
                        width: 22,
                        child: CircularProgressIndicator(
                          color: Colors.white,
                          strokeWidth: 2.5,
                        ),
                      )
                    : const Text('Confirm Booking'),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildProgressBar() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          children: [
            _buildStep(1, 'Browse', true),
            Expanded(
              child: Container(
                height: 2,
                color: const Color(AppConstants.accentColor),
              ),
            ),
            _buildStep(2, 'Profile', true),
            Expanded(
              child: Container(
                height: 2,
                color: const Color(AppConstants.accentColor),
              ),
            ),
            _buildStep(3, 'Book', true),
          ],
        ),
      ],
    );
  }

  Widget _buildStep(int n, String label, bool active) {
    return Column(
      mainAxisSize: MainAxisSize.min,
      children: [
        Container(
          width: 26,
          height: 26,
          decoration: BoxDecoration(
            color: active
                ? const Color(AppConstants.accentColor)
                : Colors.grey.shade300,
            shape: BoxShape.circle,
          ),
          alignment: Alignment.center,
          child: Text(
            '$n',
            style: TextStyle(
              color: active ? Colors.white : Colors.grey.shade600,
              fontWeight: FontWeight.bold,
              fontSize: 11,
            ),
          ),
        ),
        const SizedBox(height: 4),
        Text(
          label,
          style: TextStyle(
            fontSize: 9,
            color: active
                ? const Color(AppConstants.accentColor)
                : Colors.grey.shade400,
          ),
        ),
      ],
    );
  }

  Widget _sectionLabel(String text) => Text(
        text,
        style: const TextStyle(
          fontWeight: FontWeight.bold,
          fontSize: 15,
          color: Color(AppConstants.primaryColor),
        ),
      );
}
