// File generated by FlutterFire CLI.
// Run: `flutterfire configure` after creating your Firebase project.
//
// DO NOT edit this file manually. Replace with your actual generated values.
//
// Steps:
//  1. Go to https://console.firebase.google.com/ and create a project named "FrameFolio"
//  2. Enable Authentication > Email/Password
//  3. Create Firestore Database (start in test mode, then apply security rules)
//  4. Enable Storage
//  5. Install FlutterFire CLI:  dart pub global activate flutterfire_cli
//  6. Run: flutterfire configure --project=<your-firebase-project-id>
//  7. This file will be auto-generated and contain your real keys.
//
// The stub below lets the project compile without real Firebase credentials.
// Replace it with the auto-generated file before shipping.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for '
          '${defaultTargetPlatform.name}. '
          'Run flutterfire configure to generate options.',
        );
    }
  }

  // ─── REPLACE ALL VALUES BELOW WITH YOUR REAL FIREBASE CONFIG ───────────────

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3JslB9_f5yM91_P_H0qTE_DpYtkiIRjw',
    appId: '1:128696514938:web:68e3328142a724f74c3ec3',
    messagingSenderId: '128696514938',
    projectId: 'framefolio-efc6a',
    authDomain: 'framefolio-efc6a.firebaseapp.com',
    storageBucket: 'framefolio-efc6a.firebasestorage.app',
    measurementId: 'G-LJQZ7BERLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9YM6ddE2GtLPu9VbnsUEJTTIPi7rwWaM',
    appId: '1:128696514938:android:2be68aa270caba4f4c3ec3',
    messagingSenderId: '128696514938',
    projectId: 'framefolio-efc6a',
    storageBucket: 'framefolio-efc6a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_IOS_API_KEY',
    appId: 'REPLACE_WITH_YOUR_IOS_APP_ID',
    messagingSenderId: 'REPLACE_WITH_YOUR_SENDER_ID',
    projectId: 'REPLACE_WITH_YOUR_PROJECT_ID',
    storageBucket: 'REPLACE_WITH_YOUR_STORAGE_BUCKET',
    iosBundleId: 'com.framefolio.frameFolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_MACOS_API_KEY',
    appId: 'REPLACE_WITH_YOUR_MACOS_APP_ID',
    messagingSenderId: 'REPLACE_WITH_YOUR_SENDER_ID',
    projectId: 'REPLACE_WITH_YOUR_PROJECT_ID',
    storageBucket: 'REPLACE_WITH_YOUR_STORAGE_BUCKET',
    iosBundleId: 'com.framefolio.frameFolio',
  );
}
